# Generated by Django 4.1a1 on 2022-06-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="cost",
            new_name="total_cost",
        ),
    ]
