# Generated by Django 4.1a1 on 2022-06-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_financier"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="total_players",
            field=models.SmallIntegerField(default=8),
            preserve_default=False,
        ),
    ]
