# Generated by Django 4.1b1 on 2022-06-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_financier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
