# Generated by Django 4.1b1 on 2022-07-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.DecimalField(decimal_places=2, default=1.02, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.DecimalField(decimal_places=2, default=50.01, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=100),
        ),
    ]
