# Generated by Django 4.1b1 on 2022-07-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_latitude_event_longitude_alter_event_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name="event",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
