# Generated by Django 4.1b1 on 2022-07-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_latitude_alter_event_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="latitude",
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name="event",
            name="longitude",
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
