# Generated by Django 4.1a1 on 2022-06-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_rename_cost_event_total_cost"),
        ("jwt_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="attending",
            field=models.ManyToManyField(
                default=None, related_name="participants", to="events.event"
            ),
        ),
    ]
