# Generated by Django 4.1a1 on 2022-06-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squad", "0001_initial"),
        ("jwt_auth", "0002_user_attending"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_squads",
            field=models.ManyToManyField(
                default=2, related_name="admin_members", to="squad.squad"
            ),
        ),
    ]
