# Generated by Django 4.1b1 on 2022-06-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squad", "0002_alter_squad_venue_alter_squad_weekday"),
        ("events", "0004_event_total_players"),
        ("jwt_auth", "0003_user_admin_squads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="admin_squads",
            field=models.ManyToManyField(
                blank=True, related_name="admin_members", to="squad.squad"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="attending",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="participants", to="events.event"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="squads",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="members", to="squad.squad"
            ),
        ),
    ]
