# Generated by Django 4.0.5 on 2022-06-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('recurring', models.BooleanField(default=False)),
                ('venue', models.CharField(default=None, max_length=100)),
                ('weekday', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
