# Generated by Django 4.1a1 on 2022-06-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squad", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="squad",
            name="venue",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="squad",
            name="weekday",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
