# Generated by Django 4.1b1 on 2022-06-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squad", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="squad",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
