# Generated by Django 4.1b1 on 2022-06-22 11:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squad", "0002_alter_squad_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="squad",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image"
            ),
        ),
    ]
