# Generated by Django 4.1b1 on 2022-06-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squad", "0004_alter_squad_venue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="squad",
            name="weekday",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
