# Generated by Django 4.1b1 on 2022-07-11 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("squad", "0005_alter_squad_weekday"),
    ]

    operations = [
        migrations.AddField(
            model_name="squad",
            name="member_requests",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="squad_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
